### ISSUE TITLE
La description n'est pas trouvée dans une page où elle figure

### ISSUE THREAD

**Issue by delahousse** [irplab/irpia#139]
https://metascore.philharmoniedeparis.fr/fr/app/VKv
la description n'est pas reconnue par IRPIA
"Jeu musical pour découvrir les personnages et les instruments de musique"

**Comment by jdpro** [comment]
Le scraper ne trouve pas d'éléments pour identifier la chaîne "Jeu musical pour découvrir les personnages et les instruments de musique" comme description : elle est absente des métadonnées embarquées, n'est pas reprise dans les balises meta, et est enveloppée dans des balises sans sémantique : 
```html
<div>
          <div><p>Jeu musical pour découvrir les personnages et les instruments de musique</p></div>
</div>
```
