### ISSUE TITLE
Le type documentaire proposé ne correspond pas.

### ISSUE THREAD

**Issue by delahousse** [irplab/irpia#142]
https://metascore.philharmoniedeparis.fr/fr/app/VKv
le type documentaire proposé est "texte", il aurait du proposer "ressource interactive", la notice décrit que c'est un jeu

**Comment by jdpro** [comment]
Il n'y a pas eu, à ce stade, d'entraînement d'un modèle permettant la prédiction du type documentaire : en effet, les données d'entraînement ne le permettaient pas (presque tous les exemples se concentrent sur un seul type). En présence de données d'entraînement, ce serait simple à implémenter.
Pour l'instant, l'issue #117 a demandé que le type par défaut soit systématiquement "texte".
