### ISSUE TITLE
metascore - reconnaissance éditeur

### ISSUE THREAD

**Issue by delahousse** [irplab/irpia#143]
https://metascore.philharmoniedeparis.fr/fr/app/VKv
l'éditeur n'est pas reconnu, de nombreuses informations étaient présentes pour le trouver dont l'annotation schema.org

"publisher": {
--
  | "@type": "Organization",
  | "@id": "https://www.wikidata.org/wiki/Q3378907",
  | "name": "Cité de la musique - Philharmonie de Paris",
  | "url": "https://philharmoniedeparis.fr",
  | "sameAs": "https://www.facebook.com/PhilharmoniedeParis;",
  | "logo": {
  | "@type": "ImageObject",
  | "url": "https://philharmoniedeparis.fr/sites/default/files/logo_0.png"

**Comment by jdpro** [comment]
L'éditeur n'est pas recherché par scraping mais uniquement sur les bases SIREN - ISNI à partir des saisies utilisateurs. L'extraction du champs depuis des métadonnées embarquées dans les pages serait intéressante, malheureusement l'exemple de json-ld que tu donnes n'est jamais trouvé sur les sites des éditeurs ou les sites de ressources pédagogiques.

**Comment by delahousse** [comment]
sauf à la philharmonie :-)

Jean Delahousse
Knowledge Graph, Ontology, IA, Open Data
email ***@***.***  ***@***.***>
web *https://www.jean-delahousse.net/en/
<https://www.jean-delahousse.net/en/>*
mob +33 6 01 22 48 55
skype jean.delahousse
