### ISSUE TITLE
Les niveaux éducatifs ne sont pas suggérés alors qu'ils figurent dans la page

### ISSUE THREAD

**Issue by delahousse** [irplab/irpia#149]
https://metascore.philharmoniedeparis.fr/fr/app/yPgP
les niveaux éducatifs sont indiquées dans la page, mais pas pris en compte, IRPIA suggère 5ème et 1ere

**Comment by jdpro** [comment]
Actuellement les niveaux éducatifs sont inférés à partir du titre (saisis ou pas acceptation de suggestion). Ils ne sont pas extraits des pages par scraping.
