### ISSUE TITLE
Ne pas effacer le nom d'un contributeur non trouvé sur API SIREN/ISNI

### ISSUE THREAD

**Issue by delahousse** [irplab/irpia#150]
il semble que quand on saisie le nom d'un contributeur, non reconnu par ISNI ou Siret ce nom soit rejeté. Il ne faut pas faire cela, il faut pouvoir saisir le nom quand même : exemple auteur = Floriane Goubault

**Comment by jdpro** [comment]
C'est implémenté dans la branche 150 mais je n'ai pas mergé car en définitive cette évolution paraît problématique : si "Jean Dupont" est saisi dans le champ autocomplete, cela ne renseigne ni son "nom", ni sa "marque éditoriale" , qui sont des champs indépendants. Donc la valeur  "Jean Dupont" ne va nulle part.
