### ISSUE TITLE
Enrichissement des suggestions de niveaux

### ISSUE THREAD

**Issue by jdpro** [irplab/irpia#24]
Quand l’algorithme de suggestion classe sur les feuilles (6ème, 1ère STI2D), il faut enrichir les suggestions avec les niveaux plus génériques (cycle 2, collège, première technologique, première générale et technologique, ...) via une requête Sparql.

**Comment by delahousse** [comment]
J'ai fait la modification dans la query sur github en ajoutant 
?suggest_dom_in skos:broader ?suggest_dom_out.
Le concept père s'ajoute dans la liste des ?suggest_dom_out.
Dis moi si ca te va
Peux tu me donner/rappeler l'accès au endpoint sparql que je puisse tester
