### ISSUE TITLE
Positionnement menu autocomplete ISNI/SIREN

### ISSUE THREAD

**Issue by AlexSImon44** [irplab/irpia#66]
Contribution - propositions de l'auto-complétion 

Le listing autocomlete cache la légende du champ

**Comment by jdpro** [comment]
Après recherche aucune solution n'a été trouvé pour déplacer le "popup menu" de Mui-autocomplete sans effet de bord.
Un déroulement vers le bas n'est pas envisageable (les champs ISNI et SIREN doivent rester visibles pendant les actions utilisateur).
