### ISSUE TITLE
Couleur du contour des champs actifs 

### ISSUE THREAD

**Issue by AlexSImon44** [irplab/irpia#67]
Lorsque le champ est actif : passer le contour en ROSE principal (pas de vert, ni rouge...)

**Comment by jdpro** [comment]
Je ne trouve pas les champs concernés. Le daltonisme n'aide pas :-)
Pour moi tous les champs sont roses primary quand ils prennent le focus.

**Comment by AlexSImon44** [comment]
Cela concerne uniquement le questionnaire "contribution" : 
- le SIREN est vert
- l'ISNI est vert
- le nom éditeur est rouge
- et la marque éditoriale est rouge
Le reste étant en rose est ok.
