### ISSUE TITLE
Disposition et taille des éléments de suggestion

### ISSUE THREAD

**Issue by AlexSImon44** [irplab/irpia#73]
Formulaire / suggestions IRPIA :

- Réduire la hauteur du bandeau rose "suggestions Irpia" 
- Réduire le corps de texte blanc "Suggestions Irpia"
![Capture d’écran 2022-09-06 à 15 09 45](https://user-images.githubusercontent.com/112937067/188644297-ae4223b2-6738-4ea2-93bc-d6ec27d532c0.png)
En PJ, la page en question.

Puis :
- Augmenter la marge au-dessus des suggestions
- Réduire la taille des boutons "accepter ... " (tous les boutons de ce niveau de validation de suggestion du site également)
- Passer les boutons "accepter... " à droite
- Ajouter une croix de fermeture de la fenêtre de suggestions, blanche dans le bandeau rose, tout à droite
Voir PJ ci-dessous
<img width="778" alt="Capture d’écran 2022-09-06 à 15 15 29" src="https://user-images.githubusercontent.com/112937067/188645237-8e750eb7-8c82-4e88-a161-73e795e066e8.png">

Puis : 
- Ajouter un filet gris clair entre la liste complète déroulante fermée et les chips suggérés com
<img width="583" alt="Capture d’écran 2022-09-06 à 15 50 44" src="https://user-images.githubusercontent.com/112937067/188652715-50b7bda5-5702-454b-bf54-aedcef265a78.png">
me ci-dessous :

**Comment by jdpro** [comment]
Filet gris clair entre les suggestions acceptées et le titre du menu déroulant
