### ISSUE TITLE
Sur écran <= lg, les fleches de react-dropdown-tree-select passent à gauche

### ISSUE THREAD

**Issue by AlexSImon44** [irplab/irpia#74]
Général - Listes déroulantes : 
- Passer les flèches de liste déroulante à droite dans toutes les listes comme l'exemple que tu as suggéré sur la page contributions : (voir modèle ci-dessous)
<img width="686" alt="Capture d’écran 2022-09-06 à 15 21 26" src="https://user-images.githubusercontent.com/112937067/188646087-19168db9-2d84-4d60-aee3-cf9567c3119a.png">

Puis : 
- Réduire la taille du texte "Liste complète des...." partout et passer en gris "label" comme au-dessus des champs
- Réduire la taille du texte "taper arques lettres..." 
- Passer les "coches" bleues en rose Irpia
- Réduire la taille des items de la liste 

Capture de la page en question.
![Capture d’écran 2022-09-06 à 15 54 43](https://user-images.githubusercontent.com/112937067/188655148-c77086ad-b7d3-435e-aa34-6e283204d93b.png)

**Comment by jdpro** [comment]
Sur résolution écran < xl
