### ISSUE TITLE
Remplacer Lorem Ipsum par de vrais textes dans la notice

### ISSUE THREAD

**Issue by AlexSImon44** [irplab/irpia#77]
Formulaire - Notice - Lorem Ipsum  :
- Retirer le Loren Ipsum dans les types de ressource 
![Capture d’écran 2022-09-06 à 15 52 16](https://user-images.githubusercontent.com/112937067/188653452-9478926b-84e6-43a3-b6da-49f2786fc4e2.png)

**Comment by jdpro** [comment]
Voici les propositions  des textes pour substituer les lorem ipsum dans la notice (ticket #77):

Type documentaire
- Nature générique de la ressource

Type pédagogique
- Nature permettant de caractériser la ressource dans son contexte pédagogique
