### ISSUE TITLE
Apparence de la page veuillez choisir une vignette

### ISSUE THREAD

**Issue by AlexSImon44** [irplab/irpia#79]
Formulaire - illustrations - "Veuillez choisir une vignette" : 
- Ajouter titre en 1ère information, au-dessus du champs URL 
- Passer le contour du cadre autour du bloc "Veuillez choisir une vignette" en rose IRPIA
- Ajouter marges blanches entre chaque vignette proposée (page en question ci-desso
<img width="760" alt="Capture d’écran 2022-09-06 à 16 35 47" src="https://user-images.githubusercontent.com/112937067/188663317-ec07d3be-a421-4722-bd46-1ba5f1f987ce.png">
<img width="210" alt="Capture d’écran 2022-09-06 à 16 37 25" src="https://user-images.githubusercontent.com/112937067/188663629-a3ecfb16-36ab-456e-93b6-fb7e6c28a693.png">
- Changer couleur de survol par du Rose Irpia
- Changer couleur de la coche bleue, par du rose IRPIA (voir capture en question ci-dessous)

us)

**Comment by jdpro** [comment]
Le changement des marges est délicat : perturbe l'algorithme de positionnement du widget react-photo-gallery

**Comment by AlexSImon44** [comment]
D'accord, alors serait-il possible d'ajouter un contour blanc aux vignettes ?
